trigger:
- main
name: pals-$(Build.BuildId)

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: PackageAndBuild
    steps:
    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '17'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'
    - task: Maven@3
      inputs:
        mavenPomFile: '$(APP_NAME)/pom.xml'
        goals: 'clean package'
        options: '-Dserver.port=8080 -Dserver.host=127.0.0.1 -DTENANT-ID=$(TENANT-ID) -DSECRET=$(SECRET) -DCLIENT-ID=$(CLIENT-ID)'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        codeCoverageToolOption: 'JaCoCo'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
    - task: CopyFiles@2
      displayName: 'Copy Files to artifact staging directory'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)/$(APP_NAME)/target'
        Contents: |
          $(APP_NAME).jar
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: '$(APP_NAME)'
        publishLocation: 'Container'

- stage: Deploy
  displayName: Deploy to petpals-pals
  jobs:
  - job: Deploy
    steps:
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: '$(APP_NAME)'
        itemPattern: '**/*.jar'
        downloadPath: '$(System.ArtifactsDirectory)'
        checkDownloadedFiles: true
    - task: CopyFiles@2
      displayName: 'Copy Files from artifact staging directory'
      inputs:
        SourceFolder: '$(System.ArtifactsDirectory)/$(APP_NAME)'
        Contents: '$(APP_NAME).jar'
        TargetFolder: '$(System.DefaultWorkingDirectory)'
        OverWrite: true
    - task: AzureWebApp@1
      inputs:
        azureSubscription: 'Azure subscription 1(f1248dd5-2384-4478-bf73-b940c14b63dc)'
        appType: 'webAppLinux'
        appName: '$(APP_NAME)'
        package: '$(System.DefaultWorkingDirectory)/$(APP_NAME).jar'
        runtimeStack: 'JAVA|17-java17'
        startUpCommand: 'java -DTENANT-ID=$(TENANT-ID) -DSECRET=$(SECRET) -DCLIENT-ID=$(CLIENT-ID) -jar /home/site/wwwroot/$(APP_NAME).jar'
        appSettings: '-WEBSITES_PORT 80'
        configurationStrings: '-PORT 80'